version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - jubelio_networks
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")'"]

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - jubelio_networks

networks:
  jubelio_networks:
    external: true

volumes:
  mongo-data:
